// prettier-ignore
export const gamewords = {
    "Thức ăn": {
        "Chọn": [
            "Gà tiềm thuốc bắc",
            "Giả cầy",
            "Bánh giò",
            "Cháo lòng",
            "Bánh đúc",
            "Mì gà cá",
            "Bún đậu mắm tôm",
            "Sườn kho tiêu",
            "Lẩu mắm",
            "Bóng bàn",
            "Võ lâm truyền kỳ",
            "Đào vàng",
            "Nhảy dây",
            "Bơi lội",
            "Bắn cung",
            "Ném đĩa",
            "Cử tạ",
            "Chèo thuyền",
            "Xuân Bắc",
            "Hoài Linh",
            "Miu Lê",
            "Sơn Tùng MTP",
            "Tóc Tiên",
            "Taylor Swift",
            "Obama",
            "Bill Gates",
            "Midu",
            "Titanic",
            "Cảnh sát hình sự",
            "Home Alone",
            "Mắt biếc",
            "Ironman",
            "Tom & Jerry",
            "Joker",
            "Trái tim mùa thu",
            "Để mai tính",
            "Nơi này có anh",
            "Rồi tới luôn",
            "You raise me up",
            "Tháng 4 là lời nói dối của em",
            "Độ ta không độ nàng",
            "Cô bé mùa đông",
            "Hello",
            "Rolling in the deep",
            "Áo mới Cà mau",
            "Heo",
            "Chim bồ câu",
            "Cuốn chiếu",
            "Ngựa vằn",
            "Tê Tê",
            "Chim cánh cụt",
            "Bạch tuộc",
            "Bò cạp",
            "Đà điểu",
            "Bàn chải đánh răng",
            "Máy rửa chén",
            "Bút chì",
            "Điện thoại công cộng",
            "Máy in",
            "Sofa",
            "Gương soi",
            "Loa bluetooth",
            "Nồi Cơm điện",
            "Báo cáo",
            "Ba hoa",
            "Cung cầu",
            "Ca dao",
            "Cân bằng",
            "Mật mã",
            "Neo đơn",
            "Khẩu cung",
            "Giấy bạc",
            "Hoa hậu",
            "Hành lang",
            "Thảm thiết",
            "Ô ba ma",
            "Bóng bảy",
            "Nhật báo",
            "Dầu cá",
            "Tay trắng",
            "Xà kép",
            "Kiến thiết",
            "Mỹ nhân ngư",
            "Chân thành",
            "Gạch hoa",
            "Học đường",
            "Xe tăng",
            "Cầu mây",
            "Gấu ngựa",
            "Tình trường",
            "Hứng thú",
            "Bao hàm",
            "Kinh độ",
            "Đầu gấu",
            "Cá ngựa",
            "Mỹ Tâm",
            "Bài bạc",
            "Bao la",
            "Hỏi cung",
            "Nội gián",
            "Đầu thú",
            "Lang thang",
            "Công trái",
            "Chỉ điểm",
            "Tranh thủ",
            "Bao phủ",
            "Áp đảo",
            "Ném đá giấu tay",
            "Bỉ ổi",
            "Cổ Loa",
            "Bạc tình",
            "Chân tướng",
            "Đồng cam cộng khổ",
            "Kiếm chuyện",
            "Hồng Tâm",
            "Ngã ngũ",
            "Bao quát",
            "Trái cây",
            "Than khóc",
            "Bà xã",
            "Xích lô",
            "Nhạc cụ",
            "Hài lòng",
            "Nội thất",
            "Can gián",
            "Ngựa ô",
            "Tai họa",
            "Báo thức",
            "Xe hoa",
            "Ba đầu sáu tay",
            "Ba trợn",
            "Xương rồng",
            "Bình hoa di động",
            "Cơ bắp",
            "Bóng đá",
            "Bút ký",
            "Công bố",
            "Hành hạ",
            "Kinh lược",
            "Nhà hát",
            "Thông tấn",
            "Bà mối",
            "Ba động",
            "Áo mưa",
            "Thờ ơ",
            "Xem tướng",
            "Trâu mộng",
            "Công giáo",
            "Mũi nhọn",
            "Bao tay",
            "Ái mộ",
            "Nhân đức",
            "Đê tiện",
            "Lục lạc",
            "Tích phân",
            "Kích thích",
            "Đại tướng",
            "Bao tử",
            "Khổ tâm",
            "Ba chìm bảy nổi",
            "Anh hào",
            "Rửa tiền",
            "Ma cà rồng",
            "Báo mộng",
            "Mã hóa",
            "Tăng gia",
            "Hòm công đức",
            "Biển hiệu",
            "Bán đảo",
            "Bi hài",
            "Bi quan",
            "Mạng di động",
            "Ba chân bốn cẳng",
            "Tấn công",
            "Nhân từ",
            "Khoan hồng",
            "Quy củ",
            "Dài lưng tốn vải",
            "Môi trường",
            "Thảm họa",
            "Cao kiến",
            "Táo mèo",
            "Kéo cưa lừa xẻ",
            "U yếm",
            "Bi kịch",
            "Ba lô",
            "Xà lan",
            "Cửu tử nhất sinh",
            "Ma túy",
            "Hình bình hành",
            "Kích động",
            "Ba phải",
            "Bình chân như vại",
            "Mật khẩu",
            "Thích thú",
            "Yên bình",
            "Nặng lòng",
            "Nhãn hiệu",
            "Nhẫn tâm",
            "Kinh hoàng",
            "Hàm hậu",
            "Đào sâu",
            "Cân đẩu vân",
            "Xấu hổ",
            "Cơ hội",
            "Yêu sách",
            "Tung tăng",
            "Vườn bách thú",
            "Bắt cá hai tay",
            "Tiền đạo",
            "Nhà giáo",
            "Thượng đỉnh",
            "Ma nơ canh",
            "Họa mi",
            "Đánh lừa",
            "Liên thủ",
            "Thân thương",
            "Tranh cướp",
            "Bắt bí",
            "Yếu ớt",
            "Đình công",
            "Bánh trái",
            "Nút thắt cổ chai",
            "Hoàng thất",
            "Xà phòng",
            "Cấm kỵ",
            "Đập hộp",
            "Vĩ tuyến",
            "Nhị ca",
            "Nhà ống",
            "Chỉ số",
            "Bánh quy",
            "Ba miệng một lời",
            "Ăn mày",
            "Số trời",
            "Bào ngư",
            "Giả cầy",
            "Thư giãn",
            "Hội đồng",
            "Giải mã",
            "Triệu kiến",
            "Thiên nga",
            "Bó chân bó tay",
            "Xe điếu",
            "Ma mãnh",
            "Ô mai",
            "Thạch cao",
            "Tuần trăng mật",
            "Trái cấm",
            "Đơn độc",
            "Ma sát",
            "Táo tàu",
            "Nhà phân lô",
            "Tế bào",
            "Đồng cảm",
            "Cò cưa",
            "Kỳ quái",
            "Đao to búa lớn",
            "Nam châm",
            "Tính sổ",
            "Thú thật",
            "Tiểu thương",
            "Đường xích đạo",
            "Tưởng tượng",
            "Đông đảo",
            "Giải thích",
            "Bí truyền",
            "Bao bì",
            "Binh mã",
            "Tứ tung",
            "Gián tiếp",
            "Lịch thiệp",
            "Đờn ca tài tử",
            "Tổ tiên",
            "Thông lệ",
            "Sổ mũi",
            "Đá lửa",
            "Giá trên trời",
            "Mai mối",
            "Tay trong",
            "Ngũ cốc",
            "Cân não",
            "Một mất mười ngờ",
            "Hành hung",
            "Bí bách",
            "Cò con",
            "Thất kính",
            "Học liên thông",
            "Tối đa",
            "Hào hứng",
            "Bài xích",
            "Chỉ thị",
            "Bóng chim tăm cá",
            "Đại nhân",
            "Đám ma",
            "Sao băng",
            "Động lòng",
            "Số đào hoa",
            "Vô cơ",
            "Ý tứ",
            "Tông tích",
            "Mắc lừa",
            "Cầm cân nảy mực",
            "Bổ sung",
            "Kỳ vĩ",
            "Bảo hành",
            "Đình chỉ",
            "Tranh sơn dầu",
            "Thiếu tá",
            "Thủ tướng",
            "Hạ sĩ",
            "Binh đoàn",
            "Tổng tư lệnh",
            "Phòng không",
            "Pháo kích",
            "Lựu đạn",
            "Đấu tranh",
            "Chiến công",
            "Hỏa lực",
            "Quân hàm",
            "Tổng bí thư",
            "Thiếu tướng",
            "Lính liên lạc",
            "Hàng ngũ",
            "Tuần hành",
            "Chiến sĩ",
            "Lính đảo",
            "Chỉ huy",
            "Gián điệp",
            "Tổ quân báo",
            "Không kích",
            "Quân cơ",
            "Đánh giáp lá cà",
            "Nokia",
            "Ebay",
            "Pepsi",
            "Sam sung",
            "Yamaha",
            "Cocacola",
            "Casio",
            "Cáo buộc",
            "Cảm tử",
            "Tình cờ",
            "Ô vuông",
            "Đô la",
            "Cạnh tranh",
            "Phi cơ",
            "Hồ ly tinh",
            "Đầu mối",
            "Lông bông",
            "Sai sử",
            "Nam bán cầu",
            "Sáng sủa",
            "Mật thiết",
            "Gương cầu",
            "Đục nước béo cò",
            "Dầu gió",
            "Chiếu trúc",
            "Cát tường",
            "Xà ngang",
            "Nhãn tiền",
            "Từ bi",
            "Thủ công mỹ nghệ",
            "Ca cao",
            "Bắt cóc",
            "Báo động",
            "Đá cuội",
            "Vua phá lưới",
            "Bao la",
            "Cân nhắc",
            "Gấu quần",
            "Thiên tai",
            "Tranh cổ động",
            "Bất lợi",
            "Ô trống",
            "Tất yếu",
            "Thẳng thừng",
            "Lòng lang dạ thú",
            "Phúc hậu",
            "Táo bón",
            "Bán kính",
            "Đa tạ",
            "Độc nhất vô nhị",
            "Ho gà",
            "Hắc lào",
            "Lang ben",
            "Tiêu chảy",
            "Quai bị",
            "Trĩ nội trĩ ngoại",
            "Ép cung",
            "Đảo lộn",
            "Cao học",
            "Táo bạo",
            "Lan can",
            "Nghệ sĩ nhân dân",
            "Chín chắn",
            "Nho nhỏ",
            "La cà",
            "Cáo biệt",
            "Thích ý",
            "Hút chân không",
            "Vật tư",
            "Học lệch",
            "Bao hàm",
            "Cải tổ",
            "Đại sứ quán",
            "Tối tăm",
            "Quy chụp",
            "Ô tô",
            "Đào ngũ",
            "Mưa bóng mây",
            "Bô lão",
            "Thời hạn",
            "Tốt bụng",
            "Giao thông",
            "Một mất một còn",
            "Xơ mướp",
            "Bạch cầu",
            "Đồng bào",
            "Tỉnh táo",
            "Gương chiếu hậu",
            "Hành khúc",
            "Quy hàng",
            "Lưỡi lê",
            "Tối kỵ",
            "Nhà chọc trời",
            "Đa giác",
            "Tinh hoa",
            "Thủy đậu",
            "Đội sổ",
            "To gan lớn mật",
            "Dân phòng",
            "Hung thủ",
            "Quả báo",
            "Đánh giá",
            "Chó treo mèo đậy",
            "Cánh đồng",
            "Chân tâm",
            "Thất truyền",
            "Thần thông",
            "Sâu nặng",
            "Nho sĩ",
            "Câu cú",
            "Bạo hành",
            "Can thiệp",
            "Công ty",
            "Thiên đường",
            "Ok",
            "Gõ kiến",
            "Cầm chân",
            "Hàm hồ",
            "Hạt nhân",
            "Giấy thông hành",
            "Dân phòng",
            "Tỷ tê",
            "Quả báo",
            "Đồng bào",
            "Hành khúc",
            "Đỉnh cao",
            "Quy hàng",
            "Giao thông",
            "Nhật ký",
            "Thuốc lá",
            "Phân bổ",
            "Phân tử",
            "Lên mạng",
            "Cam kết",
            "Dao lam",
            "Nhiệt huyết",
            "Tỉnh lược",
            "Xà bông",
            "Heo hút",
            "Nhãn cầu",
            "Giao tranh",
            "Tiên đoán",
            "Yêu kiều",
            "Áp giá",
            "Bão giá",
            "Hoa lệ",
            "Cú pháp",
            "Thiên sứ",
            "Ô trọc",
            "Đá xoáy",
            "Hô hào",
            "Mất mặt",
            "Kiếm tiền",
            "Lộ liễu",
            "Trung tướng",
            "Sổ hồng",
            "Quan tâm",
            "Hoa mắt",
            "Bàn tán",
            "Tương thích",
            "Xu hướng",
            "Công công",
            "Vòi hoa sen",
            "Cửu vạn",
            "Chuẩn xác",
            "Bất ngờ",
            "Đồng đảng",
            "Trái phiếu",
            "Chim sa cá lặn",
            "Phản đối",
            "Tù mù",
            "Tí tách",
            "Nỏng nảy",
            "Kiểm kê",
            "Bè lũ",
            "Kiện tướng",
            "Họa tiết",
            "Vặn hỏi",
            "Thái độ",
            "Quy tắc",
            "Hành hình",
            "Ly biệt",
            "Mũ cánh chuồn",
            "Tên lửa",
            "Phát giác",
            "Co kéo",
            "Cau có",
            "Thánh chỉ",
            "Trường quay",
            "Nhảy lò cò",
            "Bạo lực",
            "Chim sơn ca",
            "Vô tư",
            "Giờ cao su",
            "Trung bình tấn",
            "Xã hội",
            "Phao câu",
            "Tan đàn xẻ nghé",
            "Than thở",
            "Ông bầu",
            "Cần cẩu",
            "Đại tá",
            "Bị cáo",
            "Long não",
            "Thủ đô",
            "Tỉ lệ",
            "Thất sách",
            "Vân tay",
            "Điện tích",
            "Vờ vịt",
            "Đỡ đầu",
            "Trượt bóng",
            "Bờ vai",
            "Đối tượng",
            "Chim sa cá lặn",
            "Méo mặt",
            "Họa tiết",
            "Nội soi",
            "Bay nhảy",
            "Chao đảo",
            "Đầu tư",
            "Yên nghỉ",
            "Tiền tài",
            "Điêu khắc",
            "Vô hình",
            "Thơ lục bát",
            "Vé số",
            "Phạt đền",
            "Đua thú",
            "Sổ đỏ",
            "Cao bồi",
            "Toa thuốc",
            "Tổ đỉa",
            "Khắc cốt ghi tâm",
            "Vũ trụ",
            "Con dấu",
            "Xô Viết",
            "Trụ cột gia đình",
            "Sơn hà",
            "Bánh ít",
            "Thùng rỗng kêu to",
            "Ca tụng",
            "Chữ như gà bới",
            "Rừng xanh núi đỏ",
            "Giao diện",
            "Hành tinh",
            "Quan ngại",
            "Kiến giải",
            "Ăn cơm trước kẻng",
            "Xương sống",
            "Bé bỏng",
            "Sổ nhật ký",
            "Cổ tức",
            "Tư tưởng",
            "Đào tẩu",
            "Tiền trảm hậu tấu",
            "Quán tính",
            "Tìm kiếm",
            "Vỡ mộng",
            "Cãi chày cãi cối",
            "Bán sống bán chết",
            "Trí thức",
            "Đủ lông đủ cánh",
            "Tỷ số",
            "Mặt tiền",
            "Thương hiệu",
            "Hiệu thuốc",
            "Mở màn",
            "Bèo bọt",
            "Đại hạ giá",
            "Chân thật",
            "Trung tiện",
            "Quấn quýt",
            "Bóng bàn",
            "Đá móc",
            "Tất giấy",
            "Treo giò",
            "Cầu tiêu",
            "Hôn thú",
            "Đội hình",
            "Tam cung lục viện",
            "Vĩ đại",
            "Sâu bệnh",
            "Xe ga",
            "Chuối lùn",
            "Tay sai",
            "Cầu phao",
            "Khoai nước",
            "Giàn khoan",
            "Mèo mả gà đồng",
            "Chất độc da cam",
            "Rau ngót",
            "Bản sao",
            "Viễn thông",
            "Hạn hán",
            "Lợn cắp nách",
            "Thất bại",
            "Sửa rửa mặt",
            "Đinh ba",
            "Môi hở răng lạnh",
            "Đa tình",
            "Đầm ấm",
            "Trái phép",
            "Gai góc",
            "Cây mâm xôi",
            "Ao ước",
            "Cháy bỏng",
            "Chó ăn đá gà ăn sỏi",
            "Bái kiến",
            "Chia sẻ",
            "Ga trải giường",
            "Đầu trâu mặt ngựa",
            "Thần đồng",
            "Bán độ",
            "Tranh đông hồ",
            "Kiến thức",
            "Bánh răng",
            "Xúc xích",
            "Khai thác",
            "Kim chỉ nam",
            "Hét ra lửa",
            "Sơn bóng",
            "Nhảy nhót",
            "Bu lông",
            "Tiết học",
            "Ngũ quan",
            "Thừa hành",
            "Bài học",
            "Liệt kê",
            "Xô bồ",
            "Mã não",
            "Hình sốt giá",
            "Cá nước ngọt",
            "Chấm công",
            "Trời sâu đất thẳm",
            "Thông thoáng",
            "Kích cầu",
            "Hóa thạch",
            "Mù màu",
            "Rút đơn",
            "Bom tấn",
            "Nặng tình",
            "Mỹ viện",
            "Mũ cao áo dài",
            "Sư tử biển",
            "Ông công ông táo",
            "Cau 617: Ăn cháo đá bát",
            "Đăng ký",
            "Bạn nối khố",
            "Trường điểm",
            "Thưa thớt",
            "Cầm thú",
            "Ngôi sao ca nhạc",
            "Khế ước",
            "Mua đường",
            "Chia năm xẻ bảy",
            "Huyền thoại",
            "Kem chống nắng",
            "Chân ướt chân ráo",
            "Đường chân trời",
            "Xương quai xanh",
            "Túm năm tụm ba",
            "Ướt át",
            "Đào mỏ",
            "Tẩu hỏa nhập ma",
            "Phân trần",
            "Bước sóng",
            "Rút đơn",
            "Sốt đất",
            "Bắt mắt",
            "Vùi hoa dập liễu",
            "Bàn học",
            "Nấm mộ",
            "Điện hoa",
            "Bút sa gà chết",
            "E lệ",
            "Phá rối",
            "Phấn đấu",
            "Mặt búng ra sữa",
            "Áo bà ba",
            "Khẩu độ",
            "Cải cách",
            "Hoành hành",
            "Long nhãn",
            "Nằm gai nếm mật",
            "Não ruột não gan",
            "Thạch anh",
            "Cau mày",
            "Hậu quả",
            "Hay ho",
            "Sư tử",
            "Kim cương",
            "Phản gián",
            "Đa phương tiện",
            "Coi rẻ",
            "Còi cọc",
            "Mất mạng",
            "Thông tư",
            "Triệu tập",
            "Yên tĩnh",
            "Long nhãn",
            "Mặt cắt",
            "Trái chín cây",
            "Cánh cam",
            "Căn cơ",
            "Hàn lâm",
            "Nổi gai ốc",
            "Dính quả lừa",
            "Nhà cao cửa rộng",
            "Cao niên",
            "Đài truyền hình",
            "Cao niên",
            "Cổ lỗ sĩ",
            "Bói cá",
            "Thủ thư",
            "Đau lòng",
            "Đèn kéo quân",
            "Đa sầu đa cảm",
            "Bờ rào",
            "Bánh mì gối",
            "Chắn bùn",
            "Cắm sừng",
            "Tỉnh bơ",
            "Báo tường",
            "Bông băng",
            "Thượng sách",
            "Bông băng",
            "Cá biệt",
            "Xôi xéo",
            "Bói cá",
            "Thư rác",
            "Ma mút",
            "Bỏ bùa",
            "Bó gối",
            "Cá chép",
            "Rau má",
            "Cáo già",
            "Ba que xỏ lá",
            "Hậu cần",
            "Đàn em",
            "Cá măng",
            "Hỏi gà đáp vịt",
            "Giá áo túi cơm",
            "Cổ quái",
            "Thừa tướng",
            "Giao mùa",
            "Khóa son",
            "Ăn hoa hồng",
            "Nhạc sàn",
            "Mèo già hóa cáo",
            "Cá chép",
            "Mối tình đầu",
            "Câu lạc bộ",
            "Lý lịch",
            "Mơ hồ",
            "Tai to mặt lớn",
            "Bánh trôi",
            "Trái khoáy",
            "Nhạc thính phòng",
            "Cá mập",
            "Xe mất lái",
            "Ngũ hành",
            "Đậu lướt ván",
            "Bàn đạp",
            "Thất thoát",
            "Rồng cuốn hổ ngồi",
            "Ô ăn quan",
            "Sứ giả",
            "Bao cao su",
            "Cao hứng",
            "Bánh trung thu",
            "Cười trừ",
            "Đậu đũa",
            "Chân váy",
            "Sầu thảm",
            "Nhà thương",
            "Lấy thịt đè người",
            "Mẹ đỡ đầu",
            "Túi ngủ",
            "Phá giá",
            "Sữa tươi",
            "Đánh lộn",
            "Ngắm bia",
            "Võ sư",
            "Thiếu nữ",
            "Đăng quang",
            "Chiếu chỉ",
            "Hố tử thần",
            "Trò trống",
            "No đủ",
            "Thư ký",
            "Màn hình",
            "Phân công",
            "Đàn ông",
            "Thương lái",
            "Yêu cầu",
            "Ngủ đông",
            "Thông số",
            "Lễ độ",
            "Cầm kỳ thi họa",
            "Lên voi xuống chó",
            "Chủ động",
            "Quỷ tha ma bắt",
            "Hậu trường",
            "Xúc giác",
            "Xa hoa",
            "Dư âm",
            "Học hàm",
            "Mặt báo",
            "Xuất ngũ",
            "Tốc độ",
            "Sâu sắc",
            "Treo giày",
            "Nhảy chân sáo",
            "Mã tấu",
            "Hành lễ",
            "Tổng đài",
            "Bạc mặt",
            "Miệng ăn núi lở",
            "Hát chèo",
            "Thư viện",
            "Máy nghe nhạc",
            "Trả đũa",
            "Mì tôm",
            "Thành công",
            "Ba xạo",
            "Tiền lệ",
            "Giày xéo",
            "Trứng chọi đá",
            "Hột vịt lộn",
            "Phát tài",
            "Phần mềm",
            "Nghi can",
            "Mừng thọ",
            "Bỏ bê",
            "Sốt ruột",
            "Trăng lưỡi liềm",
            "Canh me",
            "Cảm ơn",
            "Cải tiến",
            "Bong bóng nhà đất",
            "Thu nhỏ",
            "Ca tụng",
            "Cứu cánh",
            "Máy móc",
            "Trong trắng",
            "Cậu 817: Mừng thọ",
            "Vai trò",
            "Tâm bệnh",
            "Sôi động",
            "Công cụ",
            "Dương tính",
            "Quy tiên",
            "Mạng sườn",
            "Cấu trúc",
            "Cáo đội lốt cừu",
            "Học hỏi",
            "Kéo lưới",
            "Thảm cảnh",
            "Đường cách mạng",
            "Mò kim đáy bể",
            "Đại dương",
            "Quây quần",
            "Trồng cây chuối",
            "Báo lá cải",
            "Ngoại ô",
            "Khỉ ho cò gáy",
            "Máy bay bà già",
            "Bố già",
            "Xa mặt cắt lòng",
            "Nồi đồng cối đá",
            "Thấp kém",
            "Sơn tinh",
            "Gánh hát",
            "Bê tha",
            "Tượng bán thân",
            "Âm u",
            "Tổ ấm",
            "Lội ngược dòng",
            "Nhạc nước",
            "Nhật thực",
            "Vịt trời",
            "Độc đoán",
            "Đầu cơ",
            "Tre già măng mọc",
            "Bỏ phiếu",
            "Bần hàn",
            "Đãi cát tìm vàng",
            "Diêm sinh",
            "Tay hòm chìa khóa",
            "Hàm số",
            "Đường chéo",
            "Hình chiếu",
            "Diện tích",
            "Đồng tâm",
            "Hình thang",
            "Nguyên hàm",
            "Bổ đề",
            "Phép tính",
            "Hình chữ nhật",
            "Tử số",
            "Phân số",
            "Đa thức",
            "Đại số",
            "Tiền đề",
            "Khai căn",
            "Đạo hàm",
            "Hình nón",
            "Số dư",
            "Đường kính",
            "Ẩn số",
            "Phép tính",
            "Mẫu số",
            "Tam giác cân",
            "Giai thừa",
            "Góc tù",
            "Số vô tỉ",
            "Định lý",
            "Đồ thị",
            "Số hữu tỉ",
            "Thủy cung",
            "Cọp chết để da",
            "Lang băm",
            "Ấm cúng",
            "Cá nằm trên thớt",
            "Điện ảnh",
            "Thân cận",
            "Khóa sổ",
            "Tinh tường",
            "Đàn gẩy tai trâu",
            "Đánh trống bỏ dùi",
            "Xì dầu",
            "Hậu đậu",
            "Qua cầu rút ván",
            "Ngã ba đường",
            "Kiến trúc sư",
            "Anh em cọc chèo",
            "Cửa khẩu",
            "Quả địa cầu",
            "Hậu cung",
            "Cửa sổ tâm hồn",
            "Sinh lão bệnh tử",
            "Hở hàm ếch",
            "Động cơ",
            "Bịt mắt bắt dê",
            "Vẽ rắn thêm chân",
            "Bia miệng",
            "Tiểu học",
            "Lang băm",
            "Trường bán công",
            "Ca cổ",
            "Khôi ngô",
            "Tra hỏi",
            "Tình báo",
            "Điện ảnh",
            "Đàn bầu",
            "Thủ tiêu",
            "Dương lịch",
            "Siêu nhân",
            "Tử tế",
            "Chim cánh cụt",
            "Cá tháng tư",
            "Xem mặt",
            "Đè đầu cưỡi cổ",
            "Băng thông",
            "Lạc đề",
            "Thất học",
            "Đầu độc",
            "Sáo sổ lồng",
            "Diêm tiêu",
            "Vũ sư",
            "Vẽ hươu vẽ vượn",
            "Bánh bò",
            "Ăn ảnh",
            "Hạ màn",
            "Áo gió",
            "Của thiên trả địa",
            "Cửa biển",
            "Cười ra nước mắt",
            "Cầu thị",
            "Măng cụt",
            "Cầu nguyện",
            "Kẹo kéo",
            "Rồng đến nhà tôm",
            "Cao tay",
            "Tiểu nhân",
            "Cáo trạng",
            "Đấu giá",
            "Hạ màn",
            "Nhiều chuyện",
            "Ăn hỏi",
            "Động não",
            "Tiêu hóa",
            "Hoa đá",
            "Khoan khoái",
            "Yếu điểm",
            "Nước sôi lửa bỏng",
            "Mồ hôi hột",
            "Bàng quan",
            "Tiền kỳ",
            "Tiền lời",
            "Vắt chanh bỏ vỏ",
            "Tẩy não",
            "Giấy ô ly",
            "Đắt đỏ",
            "Tương kiến",
            "Hội chữ thập đỏ",
            "Nổi trống",
            "Vác mặt",
            "Mũi dọc dừa",
            "Bất công",
            "Thả hổ về rừng",
            "Thiếu nhi",
            "Kìm kẹp",
            "Sợi chỉ đỏ",
            "Ngã giá",
            "Máy bay tiêm kích",
            "Khóa chân chống",
            "Hoa tay",
            "Tức tối",
            "Tiếng Anh",
            "Giao thiệp",
            "Á khẩu",
            "Chóng mặt",
            "Đu quay",
            "Đa tài",
            "Tôm hùm",
            "Tiến độ",
            "Xuất hành",
            "Múi giờ",
            "Bàn mưu tính kế",
            "Đăng ký",
            "Thuyền rồng",
            "Tôn trọng",
            "Phật ý",
            "Cẩu thả",
            "Không quân",
            "Thân mật",
            "Bát quái",
            "Sĩ diện",
            "Viễn cảnh",
            "Diện tích",
            "Yên vui",
            "Sùng bái",
            "Yên dấu",
            "Bầu cử",
            "Hạ hỏa",
            "Lu bu",
            "Khác biệt",
            "Đường dây nóng",
            "Bảng giá",
            "Chóng mặt",
            "Lịch trình",
            "Thiên la địa võng",
            "Kiến tập",
            "Giác quan",
            "Tâm tính",
            "Hấp hối",
            "Tượng thanh",
            "Đắt đỏ",
            "Nha sĩ",
            "Va đập",
            "Ăn to nói lớn",
            "Ăn diện",
            "Khúc mắc",
            "Lân la",
            "Lược bỏ",
            "Tư cách",
            "Tôn kính",
            "Sĩ diện",
            "Tương kế tựu kế",
            "Lục đục",
            "Đánh võng",
            "Cảm tạ",
            "Hình tam giác",
            "Đồng hồ",
            "Tên cúng cơm",
            "Điều tiết",
            "Ăn năm",
            "Gia sư",
            "Tải trọng",
            "Tăng trọng",
            "Chỉ giáo",
            "Vò đầu bứt tai",
            "Động thủ",
            "Nhẫn nhịn",
            "Kế sách",
            "Phong cách",
            "Sát thủ",
            "Bình quân",
            "Đả thông",
            "Mặt hoa da phấn",
            "Mẹ tròn con vuông",
            "Điều kiện",
            "Tinh tường",
            "Tiêm phòng",
            "Đồng hành",
            "Nhà thông thái",
            "Lắm miệng",
            "Đi tắt đón đầu",
            "Lão hóa",
            "Thực tập",
            "Xích đu",
            "Chia tay",
            "Bọ gậy",
            "Thu hút",
            "Vạch lá tìm sâu",
            "m nhạc",
            "Thạch dừa",
            "Cồng kềnh",
            "Huyền bí",
            "Thăng quan",
            "Thị sát",
            "Kẻ cắp gặp bà già",
            "Thuê bao",
            "Quỷ khóc thần sầu",
            "Bia đỡ đạn",
            "Đánh răng",
            "Kỳ bí",
            "Đèn cù",
            "Bảo kê",
            "Mất tiêu",
            "Kỳ thị",
            "Tế nhị",
            "Ghen tỵ",
            "Thang máy",
            "Đồng tình",
            "Gà hoa mơ",
            "Tóc trái đào",
            "Hào quang",
            "Bè cánh",
            "Ba cọc ba đồng",
            "O bế",
            "Bóp mồm bóp miệng",
            "Siêu thị",
            "Quân tử",
            "Băng dính",
            "Đứng bóng",
            "Pháo đài",
            "Ăn không nói có",
            "Số má",
            "Chân giò",
            "Thuốc trừ sâu",
            "Giấy quỳ tím",
            "Thịt đông",
            "Ổ khóa",
            "Châu chấu đá xe",
            "Giác mạc",
            "Ăn mảnh",
            "Bóp mồm bóp miệng",
            "Cỏ gấu",
            "Ép duyên",
            "Thổ công",
            "Cuốc chim",
            "Nốt ruồi son",
            "Khai báo",
            "Đồng sàng dị mộng",
            "Đánh giày",
            "Rượu cần",
            "Thảm thương",
            "Nhãn lồng",
            "Đài hoa",
            "Khỉ gió",
            "Chào hỏi",
            "Cười ruồi",
            "Nhà in",
            "Cá nóc",
            "Cáo bạch",
            "Số đỏ",
            "Ngân sách",
            "Hành lễ",
            "Nặng ký",
            "Nhãn cầu",
            "Cây bút trẻ",
            "Góc cua",
            "Dầu dừa",
            "Lá cờ đầu",
            "Dép lê",
            "Kiến càng",
            "Cửa sổ",
            "Cầu dao",
            "Giấy bóng",
            "Cặp ba lá",
            "Điệp báo",
            "Tay nải",
            "Bánh gai",
            "Cá heo",
            "Tin vịt",
            "Trúng tủ",
            "Xấu số",
            "Cầu chì",
            "Nước nôi",
            "Cân đĩa",
            "Trúng tủ",
            "Chơi chữ",
            "Phá giá",
            "Kiến thức",
            "Canh bạc",
            "Cá hoàng đế",
            "Cà bát",
            "Lò bánh mì",
            "Lồng kính",
            "Bánh in",
            "Núp bóng",
            "Bưởi diễn",
            "Tối nghĩa",
            "Cầu may",
            "Cải cúc",
            "Nhân ái",
            "Đài sen",
            "Vàng son",
            "Chuột rút",
            "Bàn chân vàng",
            "Tóc mây",
            "Cáo thị",
            "Rắn lục",
            "Hiệu thuốc",
            "Cháo hoa",
            "Áo chống nắng",
            "Nhãn vở",
            "Thuốc bắc",
            "Măng đá",
            "Cam sành",
            "Mắc cỡ",
            "Xúc xích",
            "Móc túi",
            "Ông ba mươi",
            "Ví cầm tay",
            "Đường băng",
            "Ảnh cưới",
            "Sắn dây",
            "Đánh gió",
            "Bản sao",
            "Bếp hồng ngoại",
            "Giáp ngọ",
            "Áo gió",
            "Xe lội nước",
            "Chim cánh cụt",
            "Cầm ca",
            "Cờ lau",
            "Đo đỏ",
            "Áo dài",
            "Râu ngô",
            "Bánh tét",
            "Lá xương sông",
            "Nghệ sĩ",
            "Thú mỏ vịt",
            "Bắn pháo hoa",
            "Bánh bông lan",
            "Câu chuyện",
            "Đồng ca",
            "Cá kiếm",
            "Giáo điều",
            "Pháo đất",
            "Báo tường",
            "Điểm nóng",
            "Kem cân",
            "Tẩy não",
            "Máy tính bảng",
            "Trồng răng",
            "Thanh bạch",
            "Nóng tính",
            "Quạt thông gió",
            "Hầu bao",
            "Hỏi ý kiến",
            "Thuốc lào",
            "Thấp thoáng",
            "Đội ngũ",
            "Gối đầu",
            "Chỉ đường",
            "Lòng bàn tay",
            "Bầu khí quyển",
            "Hóa đơn",
            "Ve vãn",
            "Tập quán",
            "Hội chợ",
            "Giao điểm",
            "Hoa bằng lăng",
            "Tiêm chích",
            "Lành lặn",
            "Thuốc thang",
            "Giá lạnh",
            "Chân cầu",
            "Đèn dầu",
            "Tách bạch",
            "Cổ đông",
            "Điểm nóng",
            "Vương gia",
            "Lề đường",
            "Tết dương lịch",
            "Thông điệp",
            "Cảnh tượng",
            "Công nguyên",
            "Mai một",
            "Nhân tài",
            "Xa lắc",
            "Khai mạc",
            "Trách móc",
            "Bụng bia",
            "Kỳ tích",
            "Sao quả tạ",
            "Cầu cứu",
            "Địa điểm",
            "Trống trơn",
            "Thái độ",
            "Chống đối",
            "Cà pháo",
            "Chân lý",
            "Đại đa số",
            "Sao chép",
            "Hồ đồ",
            "Chén chú chén anh",
            "Bánh bao",
            "Từ biệt",
            "Tài hoa",
            "Cầu chúc",
            "Rối tung rối mù",
            "Cướp công",
            "Tiến sĩ",
            "Răng sữa",
            "Sâu xa",
            "Cưa sừng làm nghé",
            "Sao mai",
            "Khẩu vị",
            "Đất lành chim đậu",
            "Canh cánh",
            "Nhiệt tâm",
            "Đèn chớp",
            "Bóng đèn",
            "Bó buộc",
            "Thừa cơ",
            "Chổi lông gà",
            "Gối ôm",
            "Hoa giấy",
            "Cá voi xanh",
            "Đồng bóng",
            "Thảm bại",
            "Vui tính",
            "Chị ngã em nâng",
            "Tiêu điểm",
            "Cao huyết áp",
            "Binh thư",
            "Thực tế",
            "Trung thu",
            "Xe lửa",
            "Xe đạp điện",
            "Giao trứng cho ác",
            "Ổ gà",
            "Rau sống",
            "Kể công",
            "Đui mù",
            "Độc đáo",
            "Kỵ sĩ",
            "Cầu cạnh",
            "Điếu bát",
            "Chạy mất dép",
            "Cọp cái",
            "Chim bói cá",
            "Quan cách",
            "Độc thoại",
            "Diêm vương",
            "Huy hiệu",
            "Biển báo",
            "Thu âm",
            "Đĩa nhạc",
            "Sư tử Hà Đông",
            "Hỏi xoáy",
            "Công đường",
            "Bay nhảy",
            "Hoa thủy tiên",
            "Gia truyền",
            "Rút ruột",
            "Thẻ rút tiền",
            "Hồng quân",
            "Bảng cửu chương",
            "Nhà tù",
            "Hành tẩu",
            "Đề phòng",
            "Mảnh mai",
            "Ruột thừa",
            "Đại biểu",
            "Thượng tá",
            "Tiên phong",
            "Quân số",
            "Đóng thùng",
            "Đường mật",
            "Tiểu nhị",
            "Châm chọc",
            "Đánh cắp",
            "Chở củi về rừng",
            "Thành bại",
            "Nâng giá",
            "Bông hồng",
            "Đại bàng",
            "Đồng Hương",
            "Phân bổ",
            "Nấu sử sôi kinh",
            "Đồng bộ",
            "Câu trả lời",
            "Tay làm hàm nhai",
            "Trái cóc",
            "Trái đất",
            "Làm không công",
            "Yêu nước",
            "Gia hạn",
            "Lâu la",
            "Kê đơn",
            "Thương binh",
            "Màn đêm",
            "Bài bản",
            "Tay áo",
            "Nhà đầu tư",
            "Thượng viện",
            "Truyện cười",
            "Tư tình",
            "Bê tông",
            "Thiên vị",
            "Thủy lợi",
            "Thi công",
            "Đường cao tốc",
            "Sườn núi",
            "Báo điện tử",
            "Tâm bệnh",
            "Tử thi",
            "Kéo lê",
            "Múa ba lê",
            "Địa ốc",
            "Ngày công",
            "Bệnh tâm thần",
            "Xuất khẩu",
            "Vơ đũa cả nắm",
            "Chuông gió",
            "Gương mẫu",
            "Nguyệt thực",
            "Bẫy tình",
            "Bất nhân",
            "Trả giá",
            "Sơn hào hải vị",
            "Nhân cách",
            "Tê tái",
            "Tiêu tan",
            "Cô dâu",
            "Gà mái tơ",
            "Máy lạnh",
            "Nhạc không lời",
            "Có trăng quên đèn",
            "Thất hứa",
            "Nữ tính",
            "Yêu quái",
            "Xe tay ga",
            "Quy ước",
            "Quý giá",
            "Nghệ nhân",
            "Mê cung",
            "Tương truyền",
            "Thất thủ",
            "Nguyệt thực",
            "Chim chích bông",
            "Thiên tử",
            "Riêng biệt",
            "Phi công",
            "Thống kê",
            "Quan trọng",
            "Đổ dầu vào lửa",
            "Yếu tim",
            "Cửa sổ tình yêu",
            "Cảm tính",
            "Cốc mò cò xơi",
            "Giận cá chém thớt",
            "Long bào",
            "Tôn giáo",
            "Siêu sao",
            "Mâm cao cỗ đầy",
            "Mẫu mực",
            "Thóc cao gạo kém",
            "Xe pháo",
            "Kế sách",
            "Mồm mép tép nhảy",
            "Hút hồn",
            "Hành lý",
            "Viện trợ",
            "Quan sát",
            "Ấm no",
            "Ly gián",
            "Nhỏ cỏ tận gốc",
            "Công trường",
            "Trái thanh long",
            "Đại gia",
            "Thủ thành",
            "Quỷ cái",
            "Rách mướp",
            "Hạ cánh",
            "Cáo từ",
            "Thẻ cào",
            "Cuốn hút",
            "Chó cắn áo rách",
            "Kính vạn hoa",
            "Nhà ăn",
            "Tinh cầu",
            "Điện tâm đồ",
            "Bàn chải",
            "Đen bạc đỏ tình",
            "Hình tượng",
            "Ăn tục nói phét",
            "Rắn lục",
            "Bão giá",
            "Phải cảm",
            "Hoa loa kèn",
            "Đàn ca sáo nhị",
            "Cây cao bóng cả",
            "Giàn giáo",
            "Quần bò",
            "Mưa đá",
            "Chỉ giáo",
            "Ngư dân",
            "Lạc đàn",
            "Mỏ vàng",
            "Điện lưới",
            "Mèo già hóa cáo",
            "Phải gió",
            "Lọc lừa",
            "Lâu đài",
            "Nhà cái",
            "Lịch sử",
            "Lịch âm",
            "Gia tiên",
            "Kê chân",
            "Mai chiếu thủy",
            "Ngôi sao màn bạc",
            "Truyền hình cáp",
            "Bóp mồm bóp miệng",
            "Nam thanh nữ tú",
            "Diện kiến",
            "Nước trái cây",
            "Dao động",
            "Hành tung",
            "Mắt tròn mắt dẹt",
            "Hồng ngoại",
            "Giữ mồm giữ miệng",
            "Cá chậu chim lồng",
            "Công đoàn",
            "Cầu chì",
            "Đồng hồ điện tử",
            "Kín mít",
            "Mì chính cánh",
            "Tình hình",
            "Mày râu",
            "Chiếu lệ",
            "Giấy dầu",
            "Đường sắt",
            "Bé hạt tiêu",
            "Hàng không",
            "Viễn thị",
            "Hào hoa",
            "Chữ nho",
            "Lu mờ",
            "Màn bạc",
            "Giấy tờ",
            "Thơ lục bát",
            "Chiếu tướng",
            "Cơ quan hành pháp",
            "Xe hơi",
            "Học hàm",
            "Yếu nhân",
            "Hoa hải đường",
            "Hoa tiêu",
            "Ghế mây",
            "Súng cướp cò",
            "Thần bí",
            "Chai mặt.",
            "Than thân",
            "Ăn diện",
            "Đất đai",
            "Tập tô",
            "Đàn vĩ cầm",
            "Vô hạn",
            "Kiếm sống",
            "Học giả",
            "Bờ vai",
            "Sơ suất",
            "Va chạm",
            "Sách giáo khoa",
            "Kim tuyến",
            "Khẩu trang",
            "Thách thức",
            "Sành sòi",
            "Cao điểm",
            "Bánh kẹo",
            "Áo bông",
            "Cúc áo",
            "Tổ kiến lửa",
            "Chuột túi",
            "Đánh bắt xa bờ",
            "Dép cao su",
            "Gián đoạn",
            "Mèo mướp",
            "Vô bổ",
            "Công tơ điện",
            "Bất bình",
            "Hô hấp",
            "Bờ hồ",
            "Cá sấu",
            "Cẩu thả",
            "m thanh",
            "Đơn thuốc",
            "Mò trăng đáy nước",
            "Mẫu hậu",
            "Va ly",
            "Thủng nồi trôi dế",
            "Nước cốt",
            "Đức vua",
            "Gà đi bộ",
            "Thư tay",
            "Tư pháp",
            "Phòng khám",
            "Trò hề",
            "Bao thuốc",
            "Ca sĩ",
            "Giấy ăn",
            "Đàn tranh",
            "Nhà thiết kế",
            "Kiếm sống",
            "Mất nết",
            "Cao ốc",
            "Mỹ quan",
            "Tổng biên tập",
            "Giếng khoan",
            "Mít tinh",
            "Giấu đầu hở đuôi",
            "Cối xay gió",
            "Góp mặt",
            "Bóng đêm",
            "Giấy ăn",
            "Thật tâm",
            "Xấu tính",
            "Pháo sáng",
            "Quần bò",
            "Cối xay gió",
            "Giầy đinh",
            "Giảm giá",
            "Đội ca",
            "Xô đẩy",
            "Tổ yến",
            "Quy tập",
            "Giấy ăn",
            "Tráng lệ",
            "Địa điểm",
            "Ga tàu",
            "Bút mực",
            "Yêu thích",
            "Mỏ dầu",
            "Cảnh cáo",
            "Ly thân",
            "Bóp cò",
            "Bỏng dạ",
            "Đội ca",
            "Nhà ngoại cảm",
            "Phong thủy",
            "Sân ga",
            "Bán lẻ",
            "Dâng sao giải hạn",
            "Công trạng",
            "Nhạc cổ truyền",
            "Câu 1634:Cười vỡ bụng",
            "Súng hoa cải",
            "Quy y cửa phật",
            "Chợ búa",
            "Trái ý",
            "Nước chảy đá mòn",
            "Giật gấu vá vai",
            "Số đo",
            "Há miệng mắc quai",
            "Chín bỏ làm mười",
            "Kèm cặp",
            "Thông kim bác cổ",
            "Thùng rỗng kêu to",
            "Hà tiện",
            "Khố rách áo ôm",
            "Chiến hào",
            "Chè con ong",
            "Vạch mặt",
            "Cân móc hàm",
            "Địa chỉ",
            "Thông thoại",
            "Gà trống nuôi con",
            "Bàn bạc",
            "Kiều bào",
            "Sắc sảo",
            "Nước hoa hồng",
            "Nhất thủ nhì vĩ",
            "Tư nhân",
            "Thất bát",
            "Thất thường",
            "Phong thủy",
            "Lộng hành",
            "Tổ tông",
            "Sắc phong",
            "Nặng gánh",
            "Búa tạ",
            "Đĩa đệm",
            "Phấn hoa",
            "Cá rô đồng",
            "Hành hạ",
            "Đội ca",
            "Phá lệ",
            "Trúng số",
            "Ga lăng",
            "Trường tồn",
            "Xấu số",
            "Tâm tư",
            "Lẽ phải",
            "Điều động",
            "Gà đi bộ",
            "Siêu mẫu",
            "Đấu đá",
            "Lộn xộn",
            "Ma lực",
            "Tẩu thoát",
            "Giang sơn",
            "Thanh mai trúc mã",
            "Ăn bánh trả tiền",
            "Gia đình",
            "Tiễn biệt",
            "Điều lệ",
            "Thời tiền sử",
            "Ngã nước",
            "Thành thật",
            "Bánh hỏi",
            "Bi thảm",
            "Báo giá",
            "Hồng phúc",
            "Kết liễu",
            "Mắc cười",
            "Bảng nhãn",
            "Đồn đại",
            "Mạt cưa mướp đắng",
            "Bài tiết",
            "Ghế ngựa",
            "Đánh cá",
            "Làn sóng",
            "Nhạc đỏ",
            "Kén cá chọn canh",
            "Thanh bình",
            "Diễn văn",
            "Khoai sọ",
            "Thuốc tẩy",
            "Kinh điển",
            "Giấy than",
            "Dầu hỏa",
            "Bắp đùi",
            "Phòng cháy",
            "Thu hẹp",
            "Thỏ đế",
            "Phong lan",
            "Sát sao",
            "Thương tâm",
            "Ly hôn",
            "Thành thị",
            "Bạch kim",
            "Kính lão đắc thọ",
            "Há miệng chờ sung",
            "Đông y",
            "Cứng cáp",
            "Nói toạc móng heo",
            "Thần thoại",
            "Bình nóng lạnh",
            "Thiết bị",
            "Bách nghệ",
            "Bóng mát",
            "Nhân quả",
            "Đánh võng",
            "Nhảy dù",
            "Bánh nướng",
            "Vàng mã",
            "Đĩa cứng",
            "Biến thái",
            "Phát kiến",
            "Mít ướt",
            "Cậu ấm",
            "Đàn đá",
            "Khăn tay",
            "Điều hành",
            "Cầm sắt",
            "Cáo Giác",
            "Bông tai",
            "Niên hạn",
            "Bánh bao",
            "Ngã bệnh",
            "Câu giờ",
            "Bình bầu",
            "Cắt thuốc",
            "Họa sĩ",
            "Mật báo",
            "Lạc hậu",
            "Giấy phép",
            "Dầu mỏ",
            "Bơ phờ",
            "Bầm gan tím ruột",
            "Hồng hào",
            "Cao siêu",
            "Bom ba càng",
            "Bò sữa",
            "Y học cổ truyền",
            "Gan bàn chân",
            "Đánh bóng",
            "Gà mờ",
            "Đê điều",
            "Xuân sắc",
            "Màu cờ sắc áo",
            "Học cụ",
            "Căn nhà",
            "Tương quan",
            "Bom bi",
            "Nước ngoài",
            "Suối vàng",
            "Ảo ảnh",
            "Tắm tiên",
            "Nhất vợ nhì giời",
            "Nước mắt cá sấu",
            "Móc ngoặc",
            "Chung thủy",
            "Nhe nanh múa vuốt",
            "Mồ yên mả đẹp",
            "Quân y",
            "Mẫu giáo",
            "Hào phóng",
            "Cam thảo",
            "Thân hình",
            "Ngọc hoàng",
            "Rét run",
            "Tượng nhân sư",
            "Liên tưởng",
            "Tốt lành",
            "Thuốc tẩy",
            "Liên tỉnh",
            "Tạp hóa",
            "Bánh đậu xanh",
            "Cam ép",
            "Bóng điện",
            "Giáo án",
            "Khóa cổ",
            "Tắc đường",
            "Đầm sen",
            "Tài lẻ",
            "Cung điện",
            "Diệp lục",
            "Thức ăn",
            "Bút bi",
            "Muối mặt",
            "Kinh niên",
            "Múa ba lê",
            "Bông lau",
            "Cầm đầu",
            "Bảng hiệu",
            "Nhạc viện",
            "Yếu đuối",
            "Bơn chân không",
            "Thập niên",
            "Bố cáo",
            "Kêu ca",
            "Bàn cãi",
            "Án treo",
            "Báo cừu",
            "Kính báo",
            "Bắp chân",
            "Tẩy trắng",
            "Bách thảo",
            "Bánh xốp",
            "Ký kết",
            "Pháp y",
            "Nhà kính",
            "Tiêu điều",
            "Ngũ sắc",
            "Thất thủ",
            "Nguyên quán",
            "Bát hương",
            "Ca khúc",
            "Thừa kế",
            "Của cải",
            "Nhân tính hóa",
            "Thái dương",
            "Nóng máy",
            "Thanh cao",
            "Cân đối",
            "Hình thức",
            "Bò khô",
            "Bánh lái",
            "Kích thước",
            "Tim đập chân run",
            "Bưởi đào",
            "Cầu viện",
            "Bãi đậu xe",
            "Lắm điều",
            "Bàn giao",
            "Súng cao su",
            "Ông trời có mắt",
            "Sâu đo",
            "Ca nhạc",
            "Bò sát",
            "Đại nhạc hội",
            "Tô điểm",
            "Cần thiết",
            "Lật lọng",
            "Bóng lộn",
            "Lòng đất",
            "Quay lưng",
            "Cáo lão",
            "Đông đủ",
            "Còng số tám",
            "Thuốc nam",
            "Yên nghỉ",
            "Cánh tay",
            "Bài hát",
            "Sư thái",
            "Bằng lòng",
            "Cảnh tỉnh",
            "Bảnh bao",
            "Răng cửa",
            "Bàng hoàng",
            "Hoa anh đào",
            "Trang hoàng",
            "Thống kê",
            "Dựa dẫm",
            "Chiếu sáng",
            "Tạp âm",
            "Ôm cây đợi thỏ",
            "Phân biệt",
            "Tam giác vàng",
            "Mặt nước",
            "Tai biến",
            "Biểu tượng",
            "Đỏ mặt",
            "Cao cờ",
            "Tráng sĩ",
            "Đánh dấu",
            "Dao bầu",
            "Bất đồng",
            "Địa chỉ",
            "Thị phi",
            "Hình vẽ",
            "Lộ tẩy",
            "Nhẫn tâm",
            "Siêu thị",
            "Nhanh chóng",
            "Cám dỗ",
            "Phật lòng",
            "Kẻ cầm đầu",
            "Thông gia",
            "Dự kiến",
            "Công tâm",
            "Bênh vực",
            "Cá chậu chim lồng",
            "Tiêu khiển",
            "Thần tượng",
            "Đo ván",
            "Đầu độc",
            "Tâm trạng",
            "Mặt biển",
            "Bất động",
            "Giải thích",
            "Lê la",
            "Ví dụ",
            "Cảnh giác",
            "Long trọng",
            "Qua loa",
            "Nước hoa",
            "Điều kiện",
            "Khinh công",
            "Nổi bật",
            "Đối thủ nặng ký",
            "San sẻ",
            "Yên thân",
            "Phượng vĩ",
            "Vào sinh ra tử",
            "Che chở",
            "Câu 1946:Đuổi hình bắt chữ",
            "Thả hổ về rừng",
            "Lâm ly",
            "Tôn chỉ",
            "Đông đúc",
            "Phóng hỏa",
            "Thành quả",
            "Kết nối",
            "Mẫu mực",
            "Tinh thông",
            "Công viên",
            "Chở củi về rừng",
            "Bất chính",
            "Bí thứ",
            "Mật kế",
            "Nội tâm",
            "Hằng số",
            "Phê bình",
            "Chào hỏi",
            "Trực nhật",
            "Hành trình",
            "Phi thường",
            "Lăng kính",
            "Siêu xe",
            "Cung kính",
            "Bế tắc",
            "Biến áp",
            "Đảo chính",
            "Song hành",
            "Tức tối",
            "Hỏa công",
            "Nuôi ong tay áo",
            "Quả thật",
            "Ngọc ngà",
            "Tâm bệnh",
            "Ngoại trừ",
            "Tâm huyết",
            "Địa chủ",
            "Cử nhân",
            "Nóng tính",
            "Giấy bảo hành",
            "Gia công",
            "Ngư trường",
            "Tinh tế",
            "Mạng lưới",
            "Lo xa",
            "Kính trọng",
            "Lời ong tiếng ve",
            "Mã số",
            "Phi hành gia",
            "Mẫu giáo",
            "Lăng xăng",
            "Tử tù",
            "Hồn hậu",
            "Ý trung nhân",
            "Vàng son",
            "Hối cải",
            "Tâm tư",
            "Áo tứ thân",
            "Hạ cánh",
            "Tung hỏa mù",
            "Mai một",
            "Tổng động viên",
            "Tinh binh",
            "Vợ chồng son",
            "Bệnh nhân",
            "Đối mặt",
            "Công cốc",
            "Kỳ quan",
            "Bao che",
            "Ly kỳ",
            "Cao siêu",
            "Thu ngân",
            "Bình an",
            "Thân hình",
            "Tố giác",
            "Cơ mật",
            "Cảnh cáo",
            "Tai bay vạ gió",
            "Trống rỗng",
            "Tức nước vỡ bờ",
            "Thừa kế",
            "Buồn thảm",
            "Kêu ca",
            "Đậm đà",
            "Khoan thai",
            "Quy trình",
            "Sơn trại",
            "Gà trống nuôi con",
            "Trái tính",
            "Thực hành",
            "Tính cách",
            "Quan trọng",
            "Trống không",
            "Tiểu sử",
            "Lộ diện",
            "Tố cáo",
            "Cá độ",
            "Quần thần",
            "Quỷ kế",
            "Sâu nặng",
            "Cảnh báo",
            "Tức lộn ruột",
            "Bệnh thành tích",
            "Đáp số",
            "Hạ sách",
            "Con ông cháu cha",
            "Trống vắng",
            "Thành tích",
            "Nghệ sĩ",
            "Thành kiến",
            "Ý kiến",
            "Xa lạ",
            "Ký kết",
            "Kỳ vọng",
            "Cầu cạnh",
            "Tôn sùng",
            "Kỳ công",
            "Đàn áp",
            "Lắm mưu nhiều kế",
            "Giải phóng",
            "Đạm bạc",
            "Tập quán",
            "Mẫu mã",
            "Sôi nổi",
            "Tinh anh",
            "Nói bóng nói gió",
            "Bách hóa",
            "Bán chạy",
            "Tất thắng",
            "Ảo giác",
            "Đa tạ",
            "Đông đúc",
            "Mật thất",
            "Xe chỉ luồn kim",
            "Nhãn vở",
            "Bóng lộn",
            "Bảng chữ cái",
            "Nhiệt miệng",
            "Yên lòng",
            "Áp sát",
            "Bệnh binh",
            "Phân tâm",
            "Gia tăng",
            "Ca tụng",
            "Nổi giận",
            "Tính kế",
            "Địa bàn",
            "Phóng viên",
            "Xa xôi",
            "Thiên cơ",
            "Sâu đậm",
            "Tâm nguyện",
            "Vật cản",
            "Tế nhị",
            "Đào ao thả cá",
            "Vô danh tiểu tốt",
            "Quần đùi áo số",
            "Bất bình",
            "Cân đối",
            "Ca hát",
            "Bầu trời mặt đất",
            "Giấy mời",
            "Tứ quý",
            "Tinh nghịch",
            "Mắt cá chân",
            "Sâu xa",
            "Hà mã",
            "Quy tiên",
            "Lên đồng",
            "Hạ thủ",
            "Bạc tình",
            "Nước tiểu",
            "Á quân",
            "Ấm áp",
            "Giờ vàng",
            "An ủi",
            "Ăn bờ ở bụi",
            "Đau thương",
            "Cải cúc",
            "Phi công",
            "Ký thác",
            "Đẹp mắt",
            "Tính mạng",
            "Cơ may",
            "Vật vờ",
            "Lừa gạt",
            "Thành tâm",
            "Thiên đình",
            "Trai tráng",
            "Mặt trời lặn",
            "Thuốc tẩy",
            "Ưu tư",
            "Sao hỏa",
            "Trái mù u",
            "Đánh bạc",
            "Đông dương",
            "Chào cờ",
            "Mắt kính",
            "Ý thức",
            "Đường chỉ tay",
            "Ảo ảnh",
            "Y tế",
            "Tim tím",
            "Sai sót",
            "Thành kính",
            "Kỳ bí",
            "Làm chơi ăn thật",
            "Chân không",
            "Hồng thủy",
            "Ngũ quả",
            "Tâm can",
            "Nhạc vàng",
            "Nhà kho",
            "Than khóc",
            "Mái lật",
            "Ngoại ô",
            "Học hành",
            "Cung Nhân Mã",
            "Quạt bàn",
            "Quy chiếu",
            "Tiểu tiện",
            "Nước đổ lá khoai",
            "Mỹ nam tử",
            "Ngoại động từ",
            "Má đào",
            "Lâm bồn",
            "Tử tế",
            "Cứu cánh",
            "Lật tẩy",
            "Móc hàm",
            "Địa ốc",
            "Ngã giá",
            "Cầu hòa",
            "Kinh hồn",
            "Sáng tinh mơ",
            "Lý lịch",
            "Kỳ đà cản mũi",
            "Ướt át",
            "Hàm ý",
            "Nước tăng lực",
            "Đẹp trời",
            "Tàn tạ",
            "Vang dội",
            "Tài ba",
            "Thương gia",
            "Cáo từ",
            "Tường trình",
            "Nhỏ nhẹ",
            "Tiền mất tật mang",
            "Quy định",
            "Yên tâm",
            "Của ít lòng nhiều",
            "Tai ngược",
            "Ấm lòng",
            "Ăn to nói lớn",
            "Tự hào",
            "Tương đối",
            "Bồn chồn",
            "Ngã ba",
            "Bồng bột",
            "Lừa lọc",
            "Bê tông",
            "Lê lết",
            "La đà",
            "Ly gián",
            "Ngăn cản",
            "Hành trang",
            "Phóng đại",
            "Vô nhân tính",
            "Gánh vác",
            "Tài nghệ",
            "Xóa sổ",
            "Mập mờ",
            "Bận tâm",
            "Nhắm mắt đưa chân",
            "Cáp quang",
            "Cụ thể",
            "Đưa đẩy",
            "Khám phá",
            "Cứu tế",
            "Ma chê quỷ hờn",
            "Cầm máu",
            "Chọn lọc",
            "Thú tính",
            "Tiêu chí",
            "Na ná",
            "Câu kết",
            "Đối đáp",
            "Tiếp tay",
            "Tốt số",
            "Ho hấp",
            "Nhạc công",
            "Chạm trán",
            "Nhẹ dạ",
            "Phi cơ",
            "Hung tàn",
            "Tài nghệ",
            "Đại tiễn",
            "Tiên đồng ngọc nữ",
            "Tàn tích",
            "Tranh tài",
            "Ngang tàn",
            "Chính thức",
            "Đánh võng",
            "Ghi nhớ",
            "Sát nút",
            "Giờ cao điểm",
            "Tiêu cực",
            "Ngăn kéo",
            "Tung tích",
            "Vô địch",
            "Nhân trần",
            "Chính quy",
            "Vắng bóng",
            "Vui lòng",
            "Phòng thu",
            "Mẫu mã",
            "Can trường",
            "Máy ảnh",
            "Số đông",
            "Thâm tâm",
            "Tài nguyên",
            "Cáo trạng",
            "Phân loại",
            "Tàn dư",
            "Yên ấm",
            "Nghịch cảnh",
            "Khuyên can",
            "Bảng cáo thị",
            "Hoành hành",
            "Cầm quân",
            "Đồ thị",
            "Cây xăng",
            "Cúp cua",
            "Mạ vàng",
            "Cảm hứng",
            "Yên tâm",
            "Lông tơ",
            "Tường thuật",
            "Karaoke",
            "Ghế nóng",
            "Rối tung rối mù",
            "Bờ biển",
            "La liệt",
            "Hành tung",
            "Chia buồn",
            "Đánh động",
            "Cắt ngang",
            "Câu lệ",
            "Tự phụ",
            "Không từ thủ đoạn",
            "Băng hà",
            "Keo sơn",
            "Chính diện",
            "Sáo rỗng",
            "Tiếng tăm",
            "Bật đèn xanh",
            "Bằng khen",
            "Xe ôm",
            "Trực tiếp",
            "Dây dưa",
            "Cảm kích",
            "Công tư phân minh",
            "Bao vây",
            "Chiếu bóng",
            "Chính kiến",
            "Chí công vô tư",
            "Cầu dao",
            "Chị ngã em nâng",
            "Kết dính",
            "Chai mặt",
            "Cấm cửa",
            "E lệ",
            "Hoàng gia",
            "Kéo bè kéo phái",
            "Chỉ đạo",
            "Khổ thân",
            "Cấp phép",
            "Chết đứng",
            "Ăn hỏi",
            "Thời cơ",
            "Canh me",
            "Tiền đồ",
            "Khóc như mưa",
            "Yếu tim",
            "Tướng tiên phong",
            "Thủ tiêu",
            "Ghen tỵ",
            "Căn dặn",
            "Điệp khúc",
            "Giày vò",
            "Chạy như bay",
            "Cáo buộc",
            "Lừa tình",
            "Huy hoàng",
            "Chí hướng",
            "Đổ dầu vào lửa",
            "Bom hẹn giờ",
            "Gia cầm",
            "Cặp sách",
            "Trang điểm",
            "Công thức",
            "Hải quân",
            "Giấy phép",
            "Giả nai",
            "Bật cười",
            "Kịch tính",
            "Cử hành",
            "Vây cánh",
            "Huy động",
            "Vờ vịt",
            "Cải trang",
            "Tư nhân",
            "Kinh điển",
            "Bế mạc",
            "Thương hại",
            "Kính báo",
            "Chiếu lệ",
            "Hoa lệ",
            "Kính báo",
            "Học trò",
            "Câu cửa miệng",
            "Tên lửa",
            "Kính báo",
            "Lô cốt",
            "Điều động",
            "Lầu son",
            "Tường thành",
            "Bách tính",
            "Cửa biển",
            "Mất hút",
            "Tráng lệ",
            "Giới từ",
            "Quy tụ",
            "Liếc mắt đưa tình",
            "Đầu bạc răng long",
            "Liên đoàn",
            "Lòng lang dạ sói",
            "Quỷ sứ",
            "Biên cương",
            "Bình dân",
            "Kỳ cọ",
            "Đức lang quân",
            "Thân tàn ma dại",
            "Bà mai",
            "Xe công nông",
            "Siêu âm",
            "Nhân tiện",
            "Gầy giơ xương",
            "Máy lạnh",
            "Đại dương",
            "Rồng rắn lên mây",
            "Công cụ",
            "Biến động",
            "Số mạng",
            "Khó tính",
            "Đạp vịt",
            "Cắn câu",
            "Hoa cỏ may",
            "Tẩu thoát",
            "Run như cầy sấy",
            "Móc túi",
            "Dấu hiệu",
            "Tứ thư ngũ kinh",
            "Trượt vỏ chuối",
            "Giáo viên",
            "Đá hoa cương",
            "Nối vòng tay lớn",
            "Độc thân",
            "Cười ra nước mắt",
            "Hình thức",
            "Loại trừ",
            "Cưa sừng làm nghé",
            "Mù mờ",
            "Côn đồ",
            "Ý tưởng",
            "Cốt cách",
            "Tranh cử",
            "Tứ cố vô thân",
            "Có mắt như mù",
            "Xơ xác",
            "Nhân giống",
            "U mê",
            "Từ biệt",
            "Liên quan",
            "Kẻ bắc người nam",
            "Hoa hướng dương",
            "Trung hậu",
            "Tập đoàn",
            "Độc quyền",
            "Tích tụ",
            "Phúc đức",
            "Châm cứu",
            "Tổn thương",
            "Cậu ấm",
            "Bù lu bù loa",
            "Giới hạn",
            "Ly tán",
            "Phi nước kiệu",
            "Hình bóng",
            "Canh bạc",
            "Kẻ đón người đưa",
            "Quản lý",
            "Hàng đầu",
            "Tham gia",
            "Nổi giận",
            "Nội gián",
            "Đồng cỏ",
            "Án mạng",
            "Thuốc thang",
            "Phận bạc như vôi",
            "Cách ly",
            "Khoái khẩu",
            "Vô danh tiểu tốt",
            "Ảo não",
            "Giảm cân",
            "Bế quan",
            "Lề mề",
            "Không cam lòng",
            "Gan dạ",
            "Liên khúc",
            "Giai điệu",
            "Đội ngũ",
            "Cải chính",
            "Ma xui quỷ khiến",
            "Hiên ngang",
            "Đánh rắn động cỏ",
            "Hình hài",
            "Đơn thương độc mã",
            "Thanh toán",
            "Phân khúc",
            "Quy hàng",
            "Điệu hổ ly sơn",
            "Băng bó",
            "Đồng đội",
            "Hình chiếu",
            "Điêu tàn",
            "Từ bỏ",
            "Biên giới",
            "Công đoàn",
            "Liên lạc",
            "Du hành",
            "Câu 2489:Gần đất xa trời",
            "Gương vỡ lại lành",
            "Dối trên lừa dưới",
            "Nghịch lý",
            "Hoá đơn",
            "Vô thần",
            "Mạnh miệng",
            "Giàu tình cảm",
            "Mối lo",
            "Kinh nghiệm",
            "Ý nguyện",
            "Trung tính",
            "Vớ vẩn",
            "Sư gia",
            "Âm thầm",
            "Lạc đàn",
            "Nạn nhân",
            "Giải hạn",
            "Bàn giao",
            "Mình đồng da sắt",
            "Phản pháo",
            "Kẻ xuất gia",
            "Cộc lốc",
            "Chiếu phim",
            "Tính mạng",
            "Một lòng một dạ",
            "Hoá thạch",
            "Ca khúc",
            "Hệ quả",
            "Vô số",
            "Bảng cửu chương",
            "Cốt truyện",
            "Phản động",
            "Vội vàng",
            "Tiện lợi",
            "Hùng hổ",
            "Trăng hoa",
            "Tình nhân",
            "Bay bướm",
            "Từ bi bác ái",
            "Nhất thời",
            "E ngại",
            "Phân đoạn",
            "Cạn tàu ráo máng",
            "Cầu lông",
            "Phải lòng",
            "Bút tích",
            "Lựu đạn",
            "Tm tím",
            "Bùa hộ mạng",
            "Giải ngũ",
            "Bi quan",
            "Phao câu",
            "Quy củ",
            "Cây ăn quả",
            "Bút toán",
            "Nữ công gia chánh",
            "Lưu niệm",
            "Trước sau như một",
            "Ly dị",
            "Lấy thúng úp voi",
            "Tháp canh",
            "Hậu cung",
            "Hầu bao",
            "Chột dạ",
            "Hành hương",
            "Giai nhân",
            "Lão gia",
            "Người đi keo",
            "Hiệu nghiệm",
            "Khuyết điểm",
            "Xô đẩy",
            "Phản lực",
            "Đồng hương",
            "Tâm giao",
            "Gia hạn",
            "Hòa giải",
            "Dao động",
            "Hành tẩu",
            "Kỳ quái",
            "Thang cứu hộ",
            "Giai đoạn",
            "Hàng không",
            "Phớt lờ",
            "Kỳ thú",
            "Luật lệ",
            "Lờ mờ",
            "Suy dinh dưỡng",
            "Tĩnh tâm",
            "Công chứng",
            "Có đầu có đuôi",
            "Thiên văn",
            "Vòi nước",
            "Mùi vị",
            "Tràn lan",
            "Văn ôn võ luyện",
            "Rung cây dọa khỉ",
            "Phân bổ",
            "Nhân hậu",
            "Hành thích",
            "Đài tưởng niệm",
            "Tiểu tiết",
            "Chán cơm thèm phở",
            "Hắc ám",
            "Chai mặt",
            "Vật vờ",
            "Nhà báo",
            "Hôn nhân",
            "Hóa giải",
            "Rối rắm",
            "Đồng dao",
            "Vắng bóng",
            "Quần vợt",
            "Phê duyệt",
            "Lòng nhân ái",
            "Thủ tiêu",
            "Hành khất",
            "Muối mặt",
            "Điển trai",
            "Đông đúc",
            "Lồng lộng",
            "Cơ cực",
            "Văn phòng",
            "Vuốt ve",
            "Tăng tốc",
            "Tư gia",
            "Nắng nôi",
            "Ho lao",
            "Đào kép",
            "Rắc rối",
            "Thổi cơm",
            "Công chiếu",
            "Nhân tố",
            "Chống đẩy",
            "Đồng tính",
            "Vuốt râu hùm",
            "Ngang cơ",
            "Nét mực",
            "Sắc mặt",
            "Cứu vãn",
            "Canh phòng",
            "Đổ đốn",
            "Cam go",
            "Đúc kết",
            "Bánh nướng",
            "Lu mờ",
            "Cảm nắng",
            "Kiếm ăn",
            "Giáo trình",
            "Giải thoát",
            "Đào thảo",
            "Vô tâm",
            "Thất thu",
            "Sáng bóng",
            "Hết hồn",
            "Học thức",
            "Vượt rào",
            "Thần thái",
            "Bóng bay",
            "Đổ xô",
            "Tình cảm",
            "Vở kịch",
            "Đông dương",
            "Chớp mắt",
            "Chạy chữa",
            "Đèn giao thông",
            "Đại trà",
            "Mất lòng",
            "Đa nhân cách",
            "Thiên binh vạn mã",
            "Học vẹt",
            "Trò cười",
            "Chớp thời cơ",
            "Treo máy",
            "Xe ngựa",
            "In đậm",
            "Thuốc nhỏ mắt",
            "Tình đơn phương",
            "Đủ tư cách",
            "Đại lục",
            "Mất gốc",
            "Đèn ngủ",
            "Nhà sách",
            "Trò trống",
            "Thăng thiên",
            "Đại nhân",
            "Chữ nổi",
            "Đồng cảm",
            "Phòng thân",
            "Vui tính",
            "Tiền lệ",
            "Công lực",
            "Nâng cốc",
            "Môi giới",
            "Càn quét",
            "In dấu",
            "Đủ thứ",
            "Đạo chích",
            "Da bánh mật",
            "Mở mang",
            "Trần trụi",
            "Đơn vị",
            "Bí ẩn",
            "Hoa anh đào",
            "Chọc gậy bánh xe",
            "Máy nổ",
            "Tiền công",
            "Cháy túi",
            "Bình nguyên",
            "Thoát ly",
            "Địa đạo",
            "Yên lành",
            "Câu 2701 Vững vàng",
            "Vô hiệu hóa",
            "Máy bay bà già",
            "Té tát",
            "Quản gia",
            "Công cán",
            "Lắm trò",
            "Đóng băng",
            "Nhất thủ nhì vĩ",
            "Nổi da gà",
            "chiếc khăn gió ấm",
            "Nắng ấm xa dần",
            "Karthik",
            "Buôn Mê Thuột",
            "Số đỏ",
            "Dầu gió",
            "Ốc hương nướng mọi",
            "Hoa dâm bụt",
            "Maria Ozawa",
            "Tàu đánh cá",
            "Oẳn tù tì",
            "Bên trên tầng lầu",
            "Cô bé quàng khăn đỏ",
            "Trà sữa Alley",
            "Chuối chiên",
            "Blackberry",
            "Khai báo y tế",
            "Trái tim bên lề",
            "Đại học bách khoa",
            "Xe bus",
            "Bánh mì Huỳnh Hoa",
            "BB Trần",
            "Naruto",
            "Tom & Jerry",
            "Máu nhiễm mỡ",
            "Núi Bà Đen",
            "Tây Ban Nha"
        ]
    }
};
